debionetwork/debio-backend

- Dockerfile
- build-dev.sh
- reload-dev.sh
- Fix Dockerfile, add additional step - npm run build
- Added build-dev.sh - build and push docker image to registry
- Added reload-dev.sh - renew image, and rerun container
> ci: Build and Deploy scripts

- src/main.ts
Set application port from env to avoid port conflicts
> ci: Set application port from env

- .debio.pipeline.yml
https://blocksphere2020.atlassian.net/browse/DBIO-274
> update cicd pipeline with git approval check

- src/escrow/escrow.service.ts
- src/substrate/substrate.service.ts
get account id lab (seller_id property) from order detail, and check if balance not enough send 1 DBIO to lab
> Send gas fee DBIO to Lab on success order payment from customer

- src/recaptcha/recaptcha.controller.spec.ts
url: [https://blocksphere2020.atlassian.net/browse/DBIO-581](https://blocksphere2020.atlassian.net/browse/DBIO-581])
Create Unit Testing for Recaptcha
> BE Unit Testing : recaptcha

- src/escrow/escrow.controller.spec.ts
- src/escrow/escrow.service.spec.ts
- src/substrate/geneticTestingEvent.ts
- src/substrate/substrate.service.ts
url: [https://blocksphere2020.atlassian.net/browse/DBIO-583](https://blocksphere2020.atlassian.net/browse/DBIO-583)
Create Unit Testing escrow
replace src from location import form with '..', problem when running unit testing.
> Escrow Unit Testing

- src/substrate-indexed-data/orders/order.service.ts
https://blocksphere2020.atlassian.net/browse/DBIO-654 [[Back End] Check search function in API --> Order History]
Update order sorting by created_at descending
> search order history

- test/rating.e2e-spec.ts
https://blocksphere2020.atlassian.net/browse/DBIO-699
[Back End] Integration testing : POST /rating
> Integration testing : POST /rating 

- package-lock.json
- src/cloud-storage/cloud-storage.controller.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-809
- Added action param for GCS signed url.
> feat: add action params for gcs signed url.

- src/cloud-storage/cloud-storage.controller.ts
- src/cloud-storage/dto/data-staking.dto.ts
- src/cloud-storage/models/data-staking-sync-events.entity.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-809
- Changed event data field to filename.
> feat: changed event data field to filename.

- .debio.pipeline.yml
- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/mlc_config.json
- .github/workflows/publish-draft-release-candidate.yml
- .github/workflows/publish-draft-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/rcb_config.json
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
- .maintain/docker/Dockerfile
- Dockerfile
ci: improve workflow, add deploy job
> ci: improve workflow, add deploy job

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
ci: connect to kubernetes cluster
> ci: connect to kubernetes cluster

- src/substrate-indexed-data/orders/order.controller.ts
- src/substrate-indexed-data/orders/order.service.ts
- order service get order from elasticsearch where order bounty is true
- new get endpoint for get data bounty
> get list data bounty

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/mlc_config.json
- .github/workflows/publish-draft-release-candidate.yml
- .github/workflows/publish-draft-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/rcb_config.json
- .github/workflows/release.yml
- .maintain/docker/Dockerfile
- .maintain/docker/build-image.sh
- .maintain/docker/create-network.sh
- .maintain/docker/docker-compose.yml
- .maintain/docker/start-docker-compose.sh
- .maintain/docker/stop-docker-compose.sh
add github action workflow:
- pull request automation
- main automation --> development server
- alpha automation --> staging server
- beta automation --> preprod server
- release automation  --> production server
> ci: add github action workflow

- .dockerignore
- .maintain/docker/Dockerfile
> ci: update Dockerfile

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: improve env deploy

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
get env from google secret manager
> get env from google secret manager

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: removed unuse env

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
used swagger env dafault value
> ci: used swagger env dafault value

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: fix deployment

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
changed google service account value path
> changed google service account value path

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: remove unused code

- .github/workflows/main.yml
> ci: improve main automation

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: add new env

- src/substrate-indexed-data/orders/order.controller.ts
- src/substrate-indexed-data/orders/order.service.ts
URL to your task/ticket number in JIRA (if applicable)
If there's no JIRA ticket number, describe why in description below.
The description of your task or what is changed.
e.g: Update substrate config, new feature / bugfix, etc.
indexer order history lab, get list of index order for lab.
> Substrate Indexed data

- .github/workflows/alpha.yml
added swagger value for deployment staging
> added swagger value for deployment staging

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
https://blocksphere2020.atlassian.net/browse/DBIO-1390
add CORS and ingress basic-auth
> ci: add CORS and ingress basic-auth

- .github/workflows/pull-request.yml
N/A
update node version pr automation
> ci: update node version pr automation

- .github/workflows/beta.yml
- .github/workflows/main.yml
N/A
add ingress basic-auth dev
> ci: add ingress basic-auth dev

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: improve env

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
N/A
improve nginx ingress path
> ci: improve nginx ingress path

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
N/A
Added ingress cors-allow-headers
> ci: add ingress cors-allow-headers

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> ci: fix image repository

- src/common/mailer/mailer.manager.ts
- src/common/mailer/templates/lab-register.hbs
URL to your task/ticket number in JIRA (if applicable)
If there's no JIRA ticket number, describe why in description below.
The description of your task or what is changed.
e.g: Update substrate config, new feature / bugfix, etc.
> update email notification lab register

- src/schedulers/mailer/mailer.service.spec.ts
- src/schedulers/mailer/mailer.service.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1254
- Added email scheduler template.
> feat: mailer scheduler for future update.

- .github/workflows/deploy.yml
N/A
add new env and enable autoscaling
> ci: add new env and enable autoscaling

- .github/workflows/deploy.yml
N/A
ci: fix mainnet deployment
> ci: fix mainnet deployment

- README.md
- https://blocksphere2020.atlassian.net/browse/DBIO-1482
- Added proper minimalistic documentation to the `README.md` file.
> [DBIO-1482] docs: readme.

- .github/workflows/deploy.yml
N/A
fix docker image repository
> ci: fix docker image repository

- .github/workflows/deploy.yml
> ci: fix docker image tag

- src/common/polkadot-provider/models/index.ts
- src/common/polkadot-provider/models/service-request/index.ts
- src/common/polkadot-provider/models/service-request/request-status.ts
- src/common/polkadot-provider/query/index.ts
- src/common/polkadot-provider/query/service-request.ts
- src/schedulers/unstaked/unstaked.service.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1445
- Refactor bugfix.
> [DBIO-1445] fix: service request.

- test/unit/endpoints/location/city.service.spec.ts
- test/unit/mock.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1227
- City service unit tests.
> [DBIO-1227] tests: city service unit tests.

- test/unit/endpoints/location/location.controller.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1229
- Unit tests for location controller.
> [DBIO-1229] tests: location controller unit tests.

- .github/workflows/deploy.yml
> add new env

- .github/workflows/deploy.yml
> rename deploy command

- src/app.module.ts
- src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
- src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
- src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
- src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
- src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
- src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
- src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
- src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
- src/listeners/substrate-listener/substrate-listener.module.ts
- src/schedulers/unstaked/unstaked.service.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1445
- Fix substrate listener not working.
- Fix service created handler error.
- Fix data staked handler error.
> [DBIO-1445] fix: substrate listeners.

- src/schedulers/unstaked/unstaked.service.ts
- Accidentally commented scheduler.
> fix: uncommented scheduler.

- .github/workflows/deploy.yml
> fix helm command typo

- src/common/polkadot-provider/command/rewards.ts
URL to your task/ticket number in JIRA (if applicable)
If there's no JIRA ticket number, describe why in description below.
The description of your task or what is changed.
e.g: Update substrate config, new feature / bugfix, etc.
> bug: fixings wallet binding

- test/unit/common/modules/proxies/process-env.proxy.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1591
- Unit test process env proxy class.
> [DBIO-1591] tests: process env proxy unit tests.

- test/unit/endpoints/substrate-endpoint/services/service-request.service.spec.ts
- test/unit/mock.ts
JIRA Link
- https://blocksphere2020.atlassian.net/browse/DBIO-1606
Changelog / Description
- new export function for mock service-request.service
- unit test for service-request
> [DBIO-1606] tests: Endpoints/SubstrateEndpoints/ServiceRequest

- src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
- src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
- test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.command.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.command.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.command.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.command.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.command.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.command.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
- test/unit/mock.ts
JIRA Link
- https://blocksphere2020.atlassian.net/browse/DBIO-1609
Changelog / Description
- fix events order created and fulfilled
- add mock function for orders events
- unit testing for orders events from substrate
> [DBIO-1609] tests: Listener/OrdersEvent

- src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
- src/listeners/substrate-listener/substrate-listener.module.ts
- test/unit/@polkadot-types-interfaces.mock.ts
- test/unit/common/modules/proxies/date-time.proxy.spec.ts
- test/unit/endpoints/substrate-endpoint/services/order.service.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.command.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.command.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.command.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-waiting-for-unstaked.command.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-wating-for-unstaked.handler.spec.ts
- test/unit/listeners/substrate-listener/substrate-listener.handler.spec.ts
- test/unit/listeners/substrate-listener/substrate-listener.mock.data.ts
- test/unit/mock.ts
- test/unit/schedulers/unstaked/unstaked.service.spec.ts
JIRA Link
- https://blocksphere2020.atlassian.net/browse/DBIO-1536
Changelog / Description
- add new mock
- unit test for service request event from substrate
> [DBIO-1536] tests: Unit Test Service Request Events

- .github/workflows/rcb_config.json
- .github/workflows/tester.yml
> Improve tester

- .github/workflows/deploy.yml
- .github/workflows/tester.yml
- README.md
[URL to your task/ticket number in JIRA (if applicable)
If there's no JIRA ticket number, describe why in description below.](https://blocksphere2020.atlassian.net/browse/DBIO-1781)
add nodeSelector to deployment
> [DBIO-1781] ci: add nodeSelector to deployment

- src/endpoints/substrate-endpoint/services/service-request.service.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- test/unit/endpoints/substrate-endpoint/services/service-request.service.spec.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1813
- pagination for endpoint substrate/countries
- update unit testing service request service
> [DBIO-1813] Enhance API /substrate/countries to pagination

- src/schedulers/schedulers.module.ts
- src/schedulers/unstaked/unstaked.service.ts
- test/unit/mock.ts
- test/unit/schedulers/unstaked/unstaked.service.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-1839
- change from interval decorator to inline code
- update unit test
- add new environment variable UNSTAKE_INTERVAL
- must add new environment variable in env file (UNSTAKE_INTERVAL="milisecond")
> [DBIO-1839] Test docker di local untuk pindahin cron dari code ke env

- .github/workflows/deploy.yml
https://blocksphere2020.atlassian.net/browse/DBIO-1898
add new env
> [DBIO-1898] ci: add new env

- LICENSE
- README.md
> add AGPL-3.0 licence

- .github/workflows/deploy.yml
N/A
ci: fix deployment arguments
> ci: fix deployment arguments

- .github/workflows/deploy.yml
- N/A
- optimize deployment resource request & limit
> ci: optimize deployment resource request & limit

- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2177
- add genetic analysis order in substrate orders list response
- update unit test
> [DBIO-2177] feat : Enhance API GET /substrate/orders/list/{customer_id}

- .maintain/install-hooks.sh
- package.json
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- test/unit/@polkadot-api.mock.ts.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- test/unit/listeners/substrate-listener/substrate-listener.mock.data.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2156
- Git hooks.
- Fix formatting.
> feat: git hooks

- test/e2e/endpoints/bounty.spec.ts
- test/e2e/fixture.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2124
- integration test bounty controller
- new entities dataStakingEvents and DataTokenToDatasetMapping in dbPostgresMigration
> [DBIO-2124] Endpoint Integration Testing: Bounty Controller

- .github/workflows/builder.yml
- .github/workflows/deploy.yml
- .github/workflows/tester.yml
- [DBIO-2223]
- google auth with workload identity federation
[DBIO-2223]: https://blocksphere2020.atlassian.net/browse/DBIO-2223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DBIO-2223] ci: google auth with workload identity federation

- test/e2e/elasticsearch-fixture.ts
- test/e2e/endpoints/category/emr.spec.ts
- test/e2e/endpoints/category/service.spec.ts
- test/e2e/endpoints/category/specialization.spec.ts
- test/e2e/endpoints/substrate-endpoint.spec.ts
- test/e2e/fixture.ts
- test/e2e/setup.ts
- test/e2e/substrate-fixture.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2336
- https://blocksphere2020.atlassian.net/browse/DBIO-2337
- Fix categories integration tests import error.
- Countries substrate endpoint integration tests.
- Wallet binding substrate endpoint integration tests.
> tests: countries and wallet binding integration tests

- test/e2e/endpoints/verification.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2333
- Fix failing integration tests.
> tests: fix failing integration tests

- .github/workflows/it.yml
- https://blocksphere2020.atlassian.net/browse/DBIO-2333
- Integration tester automation Github workflow.
> ci: integration tester automation

- .github/workflows/deploy.yml
- .github/workflows/it.yml
- src/endpoints/health/health.controller.ts
- test/e2e/config.ts
- test/e2e/elasticsearch-fixture.ts
- test/e2e/endpoints/health.spec.ts
- test/e2e/fixture.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2333
- Testing...
> ci: testing it automation

- src/endpoints/health/health.controller.ts
- test/unit/endpoints/health/health.controller.spec.ts
> refactor: health check controller

- README.md
- package.json
- src/common/modules/substrate/substrate.service.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- src/endpoints/verification/verification.service.ts
- test/e2e/endpoints/health.spec.ts
- test/e2e/schedulers/mailer.spec.ts
- test/e2e/setup.ts
- test/e2e/teardown.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- test/unit/endpoints/verification/verification.service.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2333
- Add more logging.
- Fix formatting.
> tests: add more logging and fix formatting

- .github/workflows/builder.yml
- .github/workflows/deploy.yml
- N/A
- ci: add integration testing
- ci: add new env
> ci: add integration testing & new env

- src/listeners/substrate-listener/commands/labs/index.ts
- src/listeners/substrate-listener/commands/labs/registered/lab-registered.command.ts
- src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
- src/listeners/substrate-listener/commands/labs/retrieve-unstake-amount/retrieve-unstake-amount.command.ts
- src/listeners/substrate-listener/commands/labs/retrieve-unstake-amount/retrieve-unstake-amount.handler.ts
- src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.command.ts
- src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.handler.ts
- src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.command.ts
- src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.handler.ts
- src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
- src/listeners/substrate-listener/substrate-listener.handler.ts
- src/listeners/substrate-listener/substrate-listener.module.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-registered/lab-registered.command.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-registered/lab-registered.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-retrieve-unstaked-amount/lab-retrieve-unstaked-amount.command.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-retrieve-unstaked-amount/lab-retrieve-unstaked-amount.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-staked-successful/lab-stake-successful.command.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-staked-successful/lab-staked-successful.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.command.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.handler.spec.ts
- test/unit/mock.ts
- [https://blocksphere2020.atlassian.net/browse/DBIO-1778](https://blocksphere2020.atlassian.net/browse/DBIO-1778)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2451](https://blocksphere2020.atlassian.net/browse/DBIO-2451)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2452](https://blocksphere2020.atlassian.net/browse/DBIO-2452)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2497](https://blocksphere2020.atlassian.net/browse/DBIO-2497)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2498](https://blocksphere2020.atlassian.net/browse/DBIO-2498)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2499](https://blocksphere2020.atlassian.net/browse/DBIO-2499)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2500](https://blocksphere2020.atlassian.net/browse/DBIO-2 …
> feat: listener, unit test for lab & fixing forward payment to escrow when order fulfilled

- src/endpoints/substrate-endpoint/services/lab.service.ts
- test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
- [https://blocksphere2020.atlassian.net/browse/DBIO-2526](https://blocksphere2020.atlassian.net/browse/DBIO-2526)
- [feat: add field to substrate/labs and unit test](https://github.com/debionetwork/debio-backend/commit/b67ab361f0938f4087f179ff9465ae62f9a279dd)
> feat: add field to substrate/labs and unit test

- .github/workflows/deploy.yml
- N/A
- ci: improve deployment resource request
> ci: improve deployment resource request

- src/common/modules/substrate/substrate.service.ts
- test/unit/common/modules/substrate/substrate.service.spec.ts
- N/A
- [fix: fixing reconnect substrate](https://github.com/debionetwork/debio-backend/commit/a0f654859b373c437971a2f57d319ecaa0190675)
> fix : Fix reconnect to polkadot

- .github/workflows/build-failure.yml
- .github/workflows/builder.yml
- N/A
- ci: use self-hosted github action runner
> ci: use self-hosted github action runner

- .github/workflows/build-failure.yml
- .github/workflows/builder.yml
- N/A
- ci: fix github workflows
> ci: fix github workflows

- .github/workflows/build-failure.yml
- .github/workflows/builder.yml
- N/A
- ci: fix wlif permissions
> ci: fix wlif permissions

- src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
- src/listeners/substrate-listener/substrate-listener.handler.ts
- test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
- N/A
- [fix: listener and event fulfilled](https://github.com/debionetwork/debio-backend/commit/726604489e357ce50bdf0586751a2cc7c501422c)
> fix: Fix double event

- package-lock.json
- package.json
- src/common/modules/escrow/escrow.service.ts
- src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
- test/unit/common/modules/escrow/escrow.service.spec.ts
- test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
- N/A
- fix nonce and gasPrice in orderFulfilled
- fix remove forwardPaymentToSeller
> fix : fix nonce and gasPrice in orderFulfilled

- .github/workflows/deploy.yml
- .maintain/docker/Dockerfile
- https://blocksphere2020.atlassian.net/browse/DBIO-2580
- Improve Dockerfile
- Improve deployment resource request
> ci: improve dockerfile and deployment resource request

- .github/workflows/tester.yml
- package-lock.json
- package.json
- src/common/modules/transaction-logging/transaction-logging.service.ts
- src/endpoints/bounty/bounty.controller.ts
- src/endpoints/bounty/bounty.module.ts
- src/endpoints/cloud-storage/cloud-storage.controller.ts
- src/endpoints/cloud-storage/cloud-storage.module.ts
- src/endpoints/health/health.controller.ts
- src/endpoints/location/city.service.ts
- src/endpoints/verification/verification.service.ts
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
- src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.handler.ts
- test/e2e/config.ts
- test/e2e/endpoints/bounty.spec.ts
- test/e2e/endpoints/cloud-storage.spec.ts
- test/unit/common/modules/transaction-logging/transaction-logging.service.spec.ts
- test/unit/endpoints/bounty/bounty.controller.spec.ts
- test/unit/endpoints/cloud-storage/cloud-storage.controller.spec.ts
- test/unit/endpoints/health/health.controller.spec.ts
- test/unit/endpoints/location/city.service.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analysis/geneticn-analysis-result-ready/genetic-analysis-result-ready.handler.spec.ts
- test/unit/mock.ts
- [https://blocksphere2020.atlassian.net/browse/DBIO-2505](https://blocksphere2020.atlassian.net/browse/DBIO-2505)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2506](https://blocksphere2020.atlassian.net/browse/DBIO-2506)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2507](https://blocksphere2020.atlassian.net/browse/DBIO-2507)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2643](https://blocksphere2020.atlassian.net/browse/DBIO-2643)
- [https://blocksphere2020.atlassian.net/browse/DBIO-2644](https://blocksphere2020.atlassian.net/browse/DBIO-2644)
- [feat: add notification insert Request Analysis Submitted and unit test](https://github.com/debionetwork/debio-backend/commit/f3a6af2f0cf30fb516e6aaae8dc3553f477fb50f)
- [feat: add notification insert DNA Result Ready and …
> Notification

- src/endpoints/verification/verification.service.ts
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
- src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
- src/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.ts
- src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
- src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
- test/unit/endpoints/verification/verification.service.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2640
- https://blocksphere2020.atlassian.net/browse/DBIO-2639
- https://blocksphere2020.atlassian.net/browse/DBIO-2638
- https://blocksphere2020.atlassian.net/browse/DBIO-2637
- https://blocksphere2020.atlassian.net/browse/DBIO-2636
- notification new order ga
- notification verification ga (revoke, reject, verified)
- notification verification reward
> feat: notification ga

- .github/workflows/deploy.yml
> ci: update sleuth webhook

- src/endpoints/substrate-endpoint/interface/service-request.interface.ts
- src/endpoints/substrate-endpoint/services/service-request.service.ts
- 
- add country code in response
> fix: add country code in response

- package-lock.json
- package.json
- test/e2e/elasticsearch-listener-fixture.ts
- test/e2e/jest-e2e-endpoint.json
- test/e2e/jest-e2e-listener.json
- test/e2e/jest-e2e-scheduler.json
- test/e2e/listeners/substrate-listener/commands/orders/order-fulfilled.spec.ts
- test/e2e/polkadot-init.ts
- test/e2e/setup-listener.ts
- test/e2e/substrate-listener-fixture.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2699
- https://blocksphere2020.atlassian.net/browse/DBIO-2702
- Create a listener integration testing example.
- Order fulfilled event integration testing.
- 
-
> tests: order fulfilled listener integration testing

- .github/pull_request_template.md
- package-lock.json
- package.json
- src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.command.ts
- src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
- src/listeners/substrate-listener/substrate-listener.module.ts
- test/e2e/jest-e2e-listener.json
- test/e2e/listener-test-sequencer.js
- test/e2e/listeners/substrate-listener/commands/genetic-testing/data-staked.spec.ts
- test/e2e/listeners/substrate-listener/commands/orders/order-failed.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2700
- https://blocksphere2020.atlassian.net/browse/DBIO-2701
- Add order failed substrate listener integration tests.
- Add data-staked substrate listener integration tests.
- Endpoint: 
- Scheduler: 
- Listener:
> tests: order failed and data staked integration tests

- .github/workflows/deploy.yml
- N/A
- ci: improve sleuth webhook
> ci: improve sleuth webhook

- package-lock.json
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
- src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.handler.ts
- src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.handler.ts
- test/e2e/listener-test-sequencer.js
- test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created.spec.ts
- test/e2e/listeners/substrate-listener/commands/genetic-testing/data-staked.spec.ts
- test/e2e/listeners/substrate-listener/commands/labs/stake-successful.spec.ts
- test/e2e/listeners/substrate-listener/commands/labs/unstake-successful.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-staked-successful/lab-staked-successful.handler.spec.ts
- test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.handler.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2451
- https://blocksphere2020.atlassian.net/browse/DBIO-2505
- https://blocksphere2020.atlassian.net/browse/DBIO-2734
- https://blocksphere2020.atlassian.net/browse/DBIO-2735
- [fix: double row input notification submitted request test](https://github.com/debionetwork/debio-backend/commit/22693a65a88957069917adae495051deb88cfb9b)
- [test: update unit test ga order created](https://github.com/debionetwork/debio-backend/commit/7ec42dce078b5ddf062a1f355d298b3f188ca3de)
- [fix: notification unstaked and staked](https://github.com/debionetwork/debio-backend/commit/16df98cc42894b8b872787f362b7cee0c75f0ae6)
- [test: ga order created e2e test](https://github.com/debionetwork/debio-backend/pull/405/commits/9ea58560f05bd86788907efc8b8689a6db321e16 …
> fix: logging stake, unstaked and notification request analyst submitted

- src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
- test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status.spec.ts
- test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.spec.ts
- test/unit/mock.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2636
- https://blocksphere2020.atlassian.net/browse/DBIO-2638
- https://blocksphere2020.atlassian.net/browse/DBIO-2639
- ga insert notification when status change
- integration test ga verification status 
- unit test ga verification status handler
- Endpoint:
- Scheduler:
- Listener:
> feat: notification ga verification status change

- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
- test/e2e/listener-test-sequencer.js
- test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2640
- update genetic analysis paid order event
- intergation testing new order get paid to seller
- Endpoint:
- Scheduler:
- Listener:
> fix: notification genetic analysis new order paid to seller

- package-lock.json
- package.json
- src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.command.ts
- src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.handler.ts
- src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.command.ts
- src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
- test/e2e/listener-test-sequencer.js
- test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created.spec.ts
- test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid.spec.ts
- test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status.spec.ts
- test/e2e/listeners/substrate-listener/commands/genetic-testing/data-staked.spec.ts
- test/e2e/listeners/substrate-listener/commands/labs/stake-successful.spec.ts
- test/e2e/listeners/substrate-listener/commands/labs/unstake-successful.spec.ts
- test/e2e/listeners/substrate-listener/commands/orders/order-failed.spec.ts
- test/e2e/listeners/substrate-listener/commands/orders/order-fulfilled.spec.ts
- test/e2e/listeners/substrate-listener/commands/service-request/service-request-excess.spec.ts
- test/e2e/listeners/substrate-listener/commands/service-request/service-request-excess.spec.ts.txt
- test/e2e/listeners/substrate-listener/commands/service-request/service-request-partial.spec.ts
- test/e2e/listeners/substrate-listener/commands/services/service-created.spec.ts
- test/mocks/models/labs/service-request.mock.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2704
- https://blocksphere2020.atlassian.net/browse/DBIO-2750
- https://blocksphere2020.atlassian.net/browse/DBIO-2703
- https://blocksphere2020.atlassian.net/browse/DBIO-2753
- integration test service request partial
- integration test service request excess
- endpoint
- scheduler
- listener
updated
- endpoint
- scheduler
- listener
updated 2022-07-04
- endpoint
- scheduler
- listener
> test: Service Request Service Request Partial & Excess

- src/endpoints/substrate-endpoint/services/service-request.service.ts
- N/A
- [fix: endpoint substrate/countries 500](https://github.com/debionetwork/debio-backend/commit/85536171006564b471c5f0ae804e63eda0f2f60d)
- Endpoint:
- Scheduler:
- Listener:
> fix: endpoint substrate/countries 500

- .github/workflows/builder.yml
- .github/workflows/create-tags.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- .github/workflows/tester.yml
- .github/workflows/update-version.yml
- N/A
- update version automation
- code formatting
- Endpoint:
- Scheduler:
- Listener:
> ci: update version & formatting

- .github/workflows/deploy.yml
- https://blocksphere2020.atlassian.net/browse/DBIO-2820
- Added new env google project id
- Endpoint:
- Scheduler:
- Listener:
> ci: added new env google project id

- .github/workflows/deploy.yml
- N/A
- 
- Endpoint:
- Scheduler:
- Listener:
> ci: fixed project permission

- .github/workflows/deploy.yml
- https://blocksphere2020.atlassian.net/browse/DBIO-2824
- added google credential application
- Endpoint:
- Scheduler:
- Listener:
> ci: added gca

- .github/workflows/deploy.yml
- N/A
- 
- Endpoint:
- Scheduler:
- Listener:
> ci: fix helm upgrade

- package-lock.json
- package.json
> chore: bump version to 2.2.3

- package-lock.json
- src/app.module.ts
- src/common/modules/proxies/process-env/process-env.module.ts
- test/unit/common/modules/proxies/process-env.proxy.set-default.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2833
- Add a new static default function in the process env proxy.
- Endpoint:
> feat: new static default function in process env proxy

- src/app.module.ts
- 
- add name dbLocation for typeorm module
- Endpoint:
> fix: add name for typeorm module location database

- src/app.module.ts
- 
- fix env database location
- Endpoint:
> fix: database location name env

- src/endpoints/substrate-endpoint/services/lab.service.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2838
- [enhance: enpoint substrate/labs query](https://github.com/debionetwork/debio-backend/commit/1e5c701f408399a3aca404b7cf4df2d942e3bb17)
- Endpoint:
- Scheduler:
- Listener:
> enhance: enpoint substrate/labs query

- package-lock.json
- package.json
- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER
- 
- Endpoint:
- Scheduler:
- Listener:
> bump verion to 2.2.4

- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2892
- [feat: remove reward from wallet binding](https://github.com/debionetwork/debio-backend/commit/888719ada75dbf611a79102f38fb1236f9d724af)
- Endpoint: 
**NOTE: transaction e2e just success 1 of 4 times run in server**
cc: @agustinustheo @rubenkristian
> feat: remove reward from wallet binding

- src/endpoints/substrate-endpoint/interface/service-request.interface.ts
- src/endpoints/substrate-endpoint/services/service-request.service.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2936
- update field name countrycode to countryId
- not process country if request service is 0
- Endpoint:
> update field name country service request

- package-lock.json
- package.json
- src/common/modules/transaction-type/models/transaction-type.entity.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2939
- fix name column
- update package json
- Endpoint:
> fix: error parse transaction type

- src/endpoints/substrate-endpoint/interface/service-request.interface.ts
- src/endpoints/substrate-endpoint/services/service-request.service.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2936
- update substrate countries get request structure response
- Endpoint:
> fix: update response structure substrate countries

- src/common/modules/notification/notification.service.ts
- src/endpoints/notification-endpoint/dto/data-list-id.dto.ts
- src/endpoints/notification-endpoint/notification-endpoint.controller.ts
- src/endpoints/substrate-endpoint/services/lab.service.ts
- test/e2e/endpoints/notification-endpoint.spec.ts
- test/e2e/fixture.ts
- test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2968
- api for read notification by ids from client
- Endpoint:
> feat: read notification by ids

- src/endpoints/substrate-endpoint/services/lab.service.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2974
- category, region not required
- update unit test
- Endpoint:
UPDATE
> ref: substrate endpoint labs

- .github/workflows/deployer.yaml
ci: remove secrets
- N/A
- Endpoint:
- Scheduler:
- Listener:
> ci: remove secrets

- .github/pull_request_template.md
- .github/workflows/builder.yaml
- .github/workflows/mlc_config.json
- ci: fixed docker builder
- N/A
- Endpoint:
- Scheduler:
- Listener:
> ci: fixed docker builder

- src/endpoints/email/email.controller.ts
- test/e2e/endpoints/email.spec.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-2671
- Endpoint:
- Scheduler:
- Listener:
> fix: API /email/registered-genetic-analyst/{genetic_analyst_id} for send email to DAOGenics

- src/common/modules/notification/notification.service.ts
- 
- update order from updated to created
- Endpoint:
- Scheduler:
- Listener:
> fix: update order from updated to created

- .github/workflows/deployer.yaml
- README.md
ci: cleanup ssh tunneling
N/A
- Endpoint:
- Scheduler:
- Listener:
> ci: cleanup ssh tunneling

- .github/workflows/deployer.yaml
ci: fix deployer cors allow origin
N/A
- Endpoint:
- Scheduler:
- Listener:
> ci: fix deployer cors allow origin

- src/endpoints/email/email.controller.ts
- remove process.env
- get EMAILS values from google secret manager
- https://blocksphere2020.atlassian.net/browse/DBIO-2671
- Endpoint:
> fix: remove process.env and change to gcloud secret manager

- .github/workflows/deployer.yaml
ci: allow all origin on testnet
N/A
- Endpoint:
- Scheduler:
- Listener:
> ci: allow all origin on testnet

- src/common/modules/mailer/mailer.manager.ts
- src/common/modules/mailer/models/genetic-analyst-register.model/index.ts
- src/common/modules/mailer/templates/genetic-analyst-register.hbs
- fix template genetic analyst register email
- https://blocksphere2020.atlassian.net/browse/DBIO-2671
- Endpoint:
> fix: genetic analyst register template and data object

- src/endpoints/substrate-endpoint/services/lab.service.ts
- test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
- region full name
- country full name
- Endpoint:
> feat: add region and country full state name

- .github/workflows/cicd.yaml
> ci: fix actions cache

- src/endpoints/substrate-endpoint/services/lab.service.ts
- fix circular dependency
- https://blocksphere2020.atlassian.net/browse/DBIO-3116
> fix: lab substrate api

- src/endpoints/substrate-endpoint/services/lab.service.ts
- change from foreach to for loop
- https://blocksphere2020.atlassian.net/browse/DBIO-3116
> fix: lab service not show

- .github/workflows/cicd.yaml
- .github/workflows/cii.yaml
> ci: bump version gha deps

- src/endpoints/substrate-endpoint/services/index.ts
- src/endpoints/substrate-endpoint/services/menstrual-calendar.service.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- endpoint menstrual calendar
- menstrual calendar service
- https://blocksphere2020.atlassian.net/browse/DBIO-3131
> feat: endpoint menstrual calendar

- package-lock.json
- package.json
- src/common/modules/debio-conversion/debio-conversion.service.ts
- src/endpoints/pinata/pinata.controller.ts
- src/endpoints/substrate-endpoint/interface/menstrual-cycle-log.ts
- src/endpoints/substrate-endpoint/services/menstrual-calendar.service.ts
- src/endpoints/substrate-endpoint/services/service-request.service.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- fix response menstrual calendar cycle log endpoint
> fix: menstrual cycle log endpoint response

- src/endpoints/substrate-endpoint/interface/menstrual-cycle-log.ts
- src/endpoints/substrate-endpoint/services/menstrual-calendar.service.ts
> Fix: menstrual cycle log endpoint

- src/endpoints/substrate-endpoint/services/lab.service.ts
- fix issue result lab services
- https://blocksphere2020.atlassian.net/browse/DBIO-3161
> fix: result lab services

- src/common/modules/notification/notification.service.ts
- update find data in table notification with raw query
- update query to convert block_number column to int type
> fix: raw query for complex find data in table

- src/app.module.ts
- src/common/secrets/index.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.module.ts
- src/endpoints/myriad/myriad.service.ts
- tsconfig.json
- new endpoint for check username from myriad api
- new ENV myriad host endpoint
- https://blocksphere2020.atlassian.net/browse/DBIO-3255
> feat: check username from myriad api

- src/common/secrets/index.ts
- src/endpoints/myriad/dto/auth-user.dto.ts
- src/endpoints/myriad/dto/register-user.dto.ts
- src/endpoints/myriad/models/myriad-account.entity.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.module.ts
- src/endpoints/myriad/myriad.service.ts
- myriad api for register
- myriad api for auth
- entity myriad account
- https://blocksphere2020.atlassian.net/browse/DBIO-3256
- https://blocksphere2020.atlassian.net/browse/DBIO-3258
> feat: myriad api register and auth

- src/endpoints/myriad/dto/profile.dto.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- endpoint to update profile myriad
- https://blocksphere2020.atlassian.net/browse/DBIO-3261
> feat: myriad edit profile

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- add Authorization in header when edit profile request
- https://blocksphere2020.atlassian.net/browse/DBIO-3261
> fix: add auth in headers

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- new endpoint to get nonce from myriad api
- header JWT
- https://blocksphere2020.atlassian.net/browse/DBIO-3261
- https://blocksphere2020.atlassian.net/browse/DBIO-3295
> feat: endpoint api get nonce from myriad

- src/endpoints/myriad/dto/post.dto.ts
- src/endpoints/myriad/interface/post.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- endpoint api to create post to myriad
- https://blocksphere2020.atlassian.net/browse/DBIO-3260
> feat: api to create post to myriad

- src/endpoints/myriad/dto/post.dto.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- endpoint get custom timeline user
- add header jwt to endpoint create post
- fix error
- https://blocksphere2020.atlassian.net/browse/DBIO-3259
> feat: endpoint custom timeline

- src/endpoints/myriad/models/myriad-account.entity.ts
- rename table name in model entitiy
- https://blocksphere2020.atlassian.net/browse/DBIO-3256
> fix: wrong table name

- src/endpoints/myriad/models/myriad-account.entity.ts
- src/endpoints/myriad/myriad.service.ts
- fix insert account to table
- https://blocksphere2020.atlassian.net/browse/DBIO-3256
> fix: insert account

- src/app.module.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- src/endpoints/second-opinion/models/health-professional-role.entity.ts
- src/endpoints/second-opinion/models/health-professional.entity.ts
- src/endpoints/second-opinion/second-opinion.controller.ts
- src/endpoints/second-opinion/second-opinion.module.ts
- src/endpoints/second-opinion/second-opinion.service.ts
- feat second opinion health professional
- feat second opinion health professional role
- https://blocksphere2020.atlassian.net/browse/DBIO-3282
- https://blocksphere2020.atlassian.net/browse/DBIO-3281
> feat: second opinion health professional

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- change filter content unlockable
- https://blocksphere2020.atlassian.net/browse/DBIO-3278
> fix: unlockable content filter

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- src/endpoints/second-opinion/second-opinion.module.ts
- src/endpoints/second-opinion/second-opinion.service.ts
- http exception handler on error not from myriad response
- save specialization and role list to redis 
- https://blocksphere2020.atlassian.net/browse/DBIO-3260
> fix: http exception if error not from myriad

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- endpoint to check user in myriad_account table and return jwt token if user found or jwt is filled
- https://blocksphere2020.atlassian.net/browse/DBIO-3300
> feat: check user address and return jwt

- src/endpoints/myriad/myriad.controller.ts
- change role string to lower case
> fix: change to lower case

- src/endpoints/myriad/myriad.service.ts
- check error is not null
- add logger to show error in log
- https://blocksphere2020.atlassian.net/browse/DBIO-3260
[DBIO-3257]: https://blocksphere2020.atlassian.net/browse/DBIO-3257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DBIO-3260]: https://blocksphere2020.atlassian.net/browse/DBIO-3260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add logger when catch error

- src/endpoints/myriad/myriad.service.ts
- fix error 500 in post
- https://blocksphere2020.atlassian.net/browse/DBIO-3260
[DBIO-3260]: https://blocksphere2020.atlassian.net/browse/DBIO-3260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: myriad logger

- src/endpoints/myriad/myriad.service.ts
- HttpException when no user found in table account myriad
> Fix: error auth 500

- src/endpoints/myriad/dto/timeline.dto.ts
- src/endpoints/myriad/interface/timeline.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- add new endpoint to path timeline with new userid
- https://blocksphere2020.atlassian.net/browse/DBIO-3259
> feat: timeline add user

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- api endpoint total content comment
- https://blocksphere2020.atlassian.net/browse/DBIO-3275
> feat: api endpoint total content comment

- src/endpoints/myriad/interface/content.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- src/endpoints/second-opinion/second-opinion.controller.ts
- add net enpoint to get total tip user
- change field name response data
- https://blocksphere2020.atlassian.net/browse/DBIO-3277
> feat: api get total tip user

- src/endpoints/myriad/interface/user.ts
- src/endpoints/myriad/models/myriad-account.entity.ts
- src/endpoints/myriad/myriad.service.ts
- fix wrong endpoint
- update myriad entity table (add user_id column)
- get user id when register to myriad and save to table myriad account
- update check myriad account and return jwt and user_id, and set unauthorized if user_id is null or empty
- https://blocksphere2020.atlassian.net/browse/DBIO-3277
- https://blocksphere2020.atlassian.net/browse/DBIO-3256
> fix: endpoint to get tip total

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- new endpoint to get list user id by role
- https://blocksphere2020.atlassian.net/browse/DBIO-3312
> feat: list user id by role

- src/endpoints/myriad/myriad.service.ts
- add param exclusiveInfo
- https://blocksphere2020.atlassian.net/browse/DBIO-3278
> fix: add param exclusiveInfo

- src/endpoints/myriad/dto/timeline.dto.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- src/endpoints/second-opinion/models/health-professional-role.entity.ts
- change param add user timeline to myriad endpoint
- change data body to accept array string data
- https://blocksphere2020.atlassian.net/browse/DBIO-3259
> fix: change param and data body

- src/endpoints/myriad/dto/post.dto.ts
- src/endpoints/myriad/interface/post.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- add post type
- add enum Post Type
- change get timeline id by postType function
- https://blocksphere2020.atlassian.net/browse/DBIO-3313
> improvement: update create post to add post to timeline admin

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- remove jwt when add user to timeline
- get admin jwt when post request to add user to timeline
> fix: remove jwt when add user to timeline

- package-lock.json
- package.json
- src/endpoints/verification/verification.controller.ts
- src/endpoints/verification/verification.service.ts
- update polkadot-provider package
- endpoint verification health professional
- 
- https://blocksphere2020.atlassian.net/browse/DBIO-3302
> feat: verification health professional

- src/endpoints/substrate-endpoint/services/index.ts
- src/endpoints/substrate-endpoint/services/menstrual-subscription.service.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
- test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
- new endpoint to get menstrual subscription list by address id
- new service  for menstrual subscription
- add menstrual subscription service to providers
- https://blocksphere2020.atlassian.net/browse/DBIO-3332
> feat: endpoint menstrual subscription list

- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- fix variable name to get address id
- https://blocksphere2020.atlassian.net/browse/DBIO-3332
> fix: menstrual subscription list

- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- move menstrual subscription to another endpoint
- https://blocksphere2020.atlassian.net/browse/DBIO-3332
> fix: endpoint for menstrual subscription

- src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
- https://blocksphere2020.atlassian.net/browse/DBIO-3332
> fix: move menstrual subscription endpoint

- src/common/modules/mailer/mailer.manager.ts
- src/common/modules/mailer/models/currency.ts
- src/common/modules/mailer/models/genetic-analyst-register.model/service.ts
- src/common/modules/mailer/models/health-professional.model/index.ts
- src/common/modules/mailer/models/lab-register.model/service.ts
- src/common/modules/mailer/templates/health-professional-register.hbs
- Fix currency on body email
- Fix format on body email for health professional registration
- https://blocksphere2020.atlassian.net/browse/DBIO-3335
- https://blocksphere2020.atlassian.net/browse/DBIO-3334
> fix: fix currency

- src/common/modules/mailer/models/genetic-analyst-register.model/service.ts
- src/common/modules/mailer/models/lab-register.model/service.ts
- src/endpoints/myriad/myriad.module.ts
- src/endpoints/verification/dto/health-professional.dto.ts
- src/endpoints/verification/verification.controller.ts
- src/endpoints/verification/verification.module.ts
- src/endpoints/verification/verification.service.ts
- test/unit/endpoints/verification/verification.service.spec.ts
- add field to register health proffesional
- update calculate price and qc price for email
- https://blocksphere2020.atlassian.net/browse/DBIO-3333
- https://blocksphere2020.atlassian.net/browse/DBIO-3335
> fix: verified hp

- package-lock.json
- package.json
- src/common/modules/debio-conversion/debio-conversion.service.ts
> fix: conversion

- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
- add pagination and limit in unlockable content API
N/A
> feat: page & limit content unlockable

- src/endpoints/myriad/interface/auth-user.ts
- src/endpoints/myriad/myriad.service.ts
- adjustment response from myriad api auth (changed from myriad)
> fix: update auth login myriad

- src/endpoints/myriad/dto/post.dto.ts
- src/endpoints/myriad/myriad.controller.ts
- src/endpoints/myriad/myriad.service.ts
> fix: timeline not included in create post

- src/endpoints/myriad/myriad.service.ts
> fix: fix response not in json form

- src/endpoints/myriad/myriad.service.ts
> fix: issues with adding post to timeline
